SELECT
    B.AUTHOR_ID
    , AUTHOR_NAME
    , CATEGORY
    , SUM(PRICE * SALES) TOTAL_SALES
FROM
    BOOK_SALES A
    INNER JOIN BOOK B
        ON A.BOOK_ID = B.BOOK_ID
    INNER JOIN AUTHOR C
        ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE
    SALES_DATE LIKE '2022-01%'
GROUP BY
    B.AUTHOR_ID
    , CATEGORY
ORDER BY
    B.AUTHOR_ID
    , CATEGORY DESC