WITH CTE AS (
    SELECT
        *
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
)

SELECT
    A.CAR_ID
    , A.CAR_TYPE
    , FLOOR(30 * (A.DAILY_FEE * (1 - C.DISCOUNT_RATE / 100))) FEE
FROM
    CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN CTE B
        ON A.CAR_ID = B.CAR_ID 
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
        ON A.CAR_TYPE = C.CAR_TYPE
WHERE
    A.CAR_TYPE IN ('SUV', '세단')
    AND B.CAR_ID IS NULL
    AND C.DURATION_TYPE LIKE '30%'
    AND FLOOR(30 * (A.DAILY_FEE * (1 - C.DISCOUNT_RATE / 100))) BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC
    , A.CAR_TYPE
    , A.CAR_ID