SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR(30 * DAILY_FEE * (1 - (DISCOUNT_RATE / 100))) FEE
FROM
    CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN (
        SELECT
            CAR_ID
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
        ) B
            ON A.CAR_ID = B.CAR_ID
        INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
            ON A.CAR_TYPE = C.CAR_TYPE 
WHERE 
    B.CAR_ID IS NULL
    AND A.CAR_TYPE IN ('세단', 'SUV')
    AND C.DURATION_TYPE LIKE ('30%')
    AND 30 * DAILY_FEE * (1 - (DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    A.CAR_TYPE,
    A.CAR_ID DESC
