SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ',STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소,
    REGEXP_REPLACE(TLNO, '(.{3})(.{4})(.{4})', '$1-$2-$3') 전화번호
FROM
    USED_GOODS_BOARD A
    INNER JOIN USED_GOODS_USER B
        ON A.WRITER_ID = B.USER_ID
GROUP BY 
    USER_ID
HAVING 
    COUNT(USER_ID) >= 3
ORDER BY
    USER_ID DESC