SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT A.USER_ID)
FROM
    USER_INFO A
    INNER JOIN ONLINE_SALE B
        ON A.USER_ID = B.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    DATE_FORMAT(SALES_DATE, '%Y-%m'),
    GENDER
ORDER BY
    YEAR,
    MONTH,
    GENDER