SELECT
    A.PRODUCT_ID
    , PRODUCT_NAME
    , PRICE * SUM(AMOUNT) TOTAL_SALES
FROM
    FOOD_PRODUCT A
    INNER JOIN FOOD_ORDER B
        ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE
    PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC
    , PRODUCT_ID