SELECT
   A.APNT_NO,
   B.PT_NAME,
   B.PT_NO,
   C.MCDP_CD,
   C.DR_NAME,
   A.APNT_YMD
FROM
    APPOINTMENT A
    INNER JOIN PATIENT B
        ON A.PT_NO = B.PT_NO
    INNER JOIN DOCTOR C
        ON A.MDDR_ID = C.DR_ID
WHERE
    A.MCDP_CD = 'CS'
    AND A.APNT_YMD LIKE '2022-04-13%'
    AND A.APNT_CNCL_YN = 'N'
ORDER BY
    A.APNT_YMD