SELECT
    C.ID
    , C.GENOTYPE
    , P.GENOTYPE PARENT_GENOTYPE
FROM
    ECOLI_DATA C
    INNER JOIN ECOLI_DATA P
        ON C.PARENT_ID = P.ID
WHERE
    C.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY
    C.ID