SELECT
    MONTH(START_DATE) MONTH,
    CAR_ID,
    COUNT(CAR_ID) RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID IN(
        SELECT
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY
            CAR_ID
        HAVING
            SUM(MONTH(START_DATE) BETWEEN 8 AND 10) >= 5
    )
GROUP BY
    MONTH,
    CAR_ID
HAVING
    MONTH BETWEEN 8 AND 10
ORDER BY
    MONTH,
    CAR_ID DESC
