-- CONV(INT, N, M) N진수로 표현된 INT를 M진수로 변환
SELECT
    ID
    , EMAIL
    , FIRST_NAME
    , LAST_NAME
FROM
    DEVELOPERS
WHERE
    IF(SKILL_CODE > 256, RIGHT(CONV(SKILL_CODE, 10, 2), 9) LIKE '1%'
    OR RIGHT(CONV(SKILL_CODE, 10, 2), 11) LIKE '1%')
ORDER BY
    ID