WITH MAX_TABLE AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) YEAR
        , MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
)

SELECT
    YEAR(DIFFERENTIATION_DATE) YEAR
    , ((SELECT MAX_SIZE FROM MAX_TABLE WHERE YEAR = YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) YEAR_DEV
    , ID
FROM
    ECOLI_DATA
ORDER BY
    YEAR
    , YEAR_DEV