SELECT
    DISTINCT A.FLAVOR
FROM
    FIRST_HALF A
    INNER JOIN ICECREAM_INFO B
        ON A.FLAVOR = B.FLAVOR
WHERE
    TOTAL_ORDER > 3000
    AND INGREDIENT_TYPE = 'fruit_based'
GROUP BY
    A.FLAVOR
ORDER BY
    TOTAL_ORDER DESC