SELECT
    A.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR A
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        ON A.CAR_ID = B.CAR_ID
WHERE 
    MONTH(START_DATE) = '10'
    AND CAR_TYPE = '세단'
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC