WITH HIGHEST AS (
    SELECT
        EMP_NO
        , SUM(SCORE) SCORE
    FROM
        HR_GRADE
    WHERE
        YEAR = '2022'
    GROUP BY
        EMP_NO
    ORDER BY
        SUM(SCORE) DESC
    LIMIT 1
)

SELECT
    B.SCORE
    , A.EMP_NO
    , A.EMP_NAME
    , A.POSITION
    , A.EMAIL
FROM
    HR_EMPLOYEES A
    INNER JOIN HIGHEST B
        ON A.EMP_NO = B.EMP_NO