SELECT
    CATEGORY
    , SUM(SALES) TOTAL_SALES
FROM
    BOOK A
    INNER JOIN BOOK_SALES B
        ON A.BOOK_ID = B.BOOK_ID
WHERE
    SALES_DATE LIKE '2022-01%'
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY